version: "3"

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # Change this
      MYSQL_DATABASE: my_database # Change this
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root # Change this
      - DATABASE_NAME=my_database
    depends_on:
      - mysql

volumes:
  db_data:
